network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      addresses:
        - 192.168.1.93/24
      nameservers:
        addresses:
          - 1.1.1.1
      routes:
        - to: default
          via: 192.168.1.1
  bridges:
    NMN_BLUE:
      dhcp4: false
      addresses:
        - 10.252.0.1/24
      macaddress: '08:00:27:4b:1d:46'
      parameters:
        stp: false
      dhcp6: false
    # NMN:
    #   dhcp4: false
    #   addresses:
    #     - 10.252.10.0/31
    #   macaddress: '08:00:27:4b:1d:45'
    #   parameters:
    #     stp: false
    #   dhcp6: false
  #   NMN_GREEN:
  #     dhcp4: false
  #     addresses:
  #       - 10.252.0.11/24
  #     macaddress: '08:00:27:4b:1d:57'
  #     parameters:
  #       stp: false
  #     dhcp6: false
#  vrfs:
#    vrf-green:
#      table: 10
#      interfaces:
#        - NMN_GREEN
  # tunnels:
  #   vxlan20:
  #     mode: vxlan
  #     local: 10.10.10.1
  #     port: 4789
  #     id: 110
  #     link: NMN_BLUE
  #     mac-learning: false
  #     accept-ra: 'no'